### ISSUE TITLE
go-polyglot plugin fail with a error

### ISSUE THREAD

**Issue by nicolaenicora** [loopholelabs/polyglot#27]
Hi Team,

`
protoc --plugin=protoc-gen-go-polyglot=$GOBIN/protoc-gen-go-polyglot --go-polyglot_out=. echo.proto
panic: template: headers.templ:2:33: executing "headers" at <{{.pluginVersion}}>: can't print {{.pluginVersion}} of type func() string

goroutine 1 [running]:
main.main()
        /Users/GoLib/src/github.com/loopholelabs/polyglot/protoc-gen-go-polyglot/main.go:41 +0x11a
--go-polyglot_out: protoc-gen-go-polyglot: Plugin failed with status code 2.

`

Where:
https://github.com/loopholelabs/polyglot/blob/staging/generator/golang/generator.go#L120
should be ´"pluginVersion":   version.Version -> version.Version()´

**Comment by ShivanshVij** [comment]
Fixed in v1.1.4
